"""initial holdings table

Revision ID: 604fd741d959
Revises: 
Create Date: 2026-05-10 17:55:42.731520

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '604fd741d959'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.drop_table('holdings')
    # ### end Alembic commands ###
